### ISSUE TITLE
Use WORLD vocoder spec env

### ISSUE THREAD

**Issue by gillesdegottex** [gillesdegottex/pulsemodel#12]

**Comment by gillesdegottex** [comment]
done in v1.1.0

**Comment by ljuvela** [comment]
When first trying to build with `make build_pyworld` I was getting 
pyworld/pyworld.cpp:451:29: fatal error: world/synthesis.h: No such file or directory

To fix this, I went to `external/pyworld` and ran `git submodule update --init`
This should be handled automatically?

**Comment by gillesdegottex** [comment]
--recursive was missing.
Thanks!
