### ISSUE TITLE
Error encountered when run synthesis.py  (File "synthesis.py", line 178, in synthesize)

### ISSUE THREAD

**Issue by dengliqun** [gillesdegottex/pulsemodel#21]
I got the following errors when run the copy-synthesis with the "awb_arctic_a0040.wav" example.
Traceback (most recent call last):
  File "synthesis.py", line 374, in <module>
    main(sys.argv[1:])
  File "synthesis.py", line 371, in main
    synthesizef(args.fs, shift=args.shift, dftlen=args.dftlen, ff0=args.f0, flf0=args.logf0, fspec=args.spec, ffwlspec=args.fwlspec, ffwcep=args.fwcep, fmcep=args.mcep, fnm=args.nm, ffwnm=args.fwnm, nm_cont=args.nm_cont, fpdd=args.pdd, fmpdd=args.mpdd, fsyn=args.synth, verbose=args.verbose)
  File "synthesis.py", line 340, in synthesizef
    syn = synthesize(fs, f0s, SPEC, NM=NM, nm_cont=nm_cont, verbose=verbose)
  File "synthesis.py", line 178, in synthesize
    if winlen>dftlen: raise ValueError('winlen({})>dftlen({})'.format(winlen, dftlen)) # pragma: no cover
ValueError: winlen(801)>dftlen(118)

I got the f0 spec and nm features with the analysis,py (i'm sure pyworld is used), 
analysisf("awb_arctic_a0040.wav",
              shift=args.shift,
              dftlen=args.dftlen,
              finf0txt=args.inf0txt, f0_min=args.f0_min, f0_max=args.f0_max, ff0="awb_arctic_a0040.f0", f0_log=args.f0_log,
              finf0bin=args.inf0bin,
              fspec="awb_arctic_a0040.spec", spec_mceporder=59, spec_fwceporder=args.spec_fwceporder, spec_nbfwbnds=args.spec_nbfwbnds,
              fpdd="pdd/"+fileid+".pdd", pdd_mceporder=59,
              fnm="awb_arctic_a0040.nm", nm_nbfwbnds=None,
              preproc_fs=args.preproc_fs, preproc_hp=args.preproc_hp,
              verbose=args.verbose)

and run the synthesis command as 
python synthesis.py awb_arctic_a0040.resyn.wav --f0 awb_arctic_a0040.f0 --spec awb_arctic_a0040.spec --nm awb_arctic_a0040.nm

Please help.  Thx.

**Comment by gillesdegottex** [comment]
Did you replace the f0 estimator? Maybe changed the minimum value for f0?

I've updated the master with a fix for this case and some warning. please pull the master's updates.

**Comment by dengliqun** [comment]
@gillesdegottex  Thanks much for your reply. I used the REAPER estimator as recommended by default. I have updated to the latest version, but is seems that the same error still exists.

**Comment by gillesdegottex** [comment]
If you analyse with --nm_nbfwbnds, you have to use --fwnm then during synthesis.
Same for --spec_mceporder that needs --mcep at synthesis.
Try this first and tell me if there any more errors.

**Comment by gillesdegottex** [comment]
Seems to be solved.
