### ISSUE TITLE
Vocoder type

### ISSUE THREAD

**Issue by Ali20177** [gillesdegottex/pulsemodel#6]
Dear all,

Does this type of vocoder considered as a source filter model or sinusoidal model?

Thank you very much in advance

**Comment by gillesdegottex** [comment]
source filter model, but with the '+' happening in log domain.

**Comment by gillesdegottex** [comment]
just to precise: as a consequence, it is neither the traditional source filter model nor sinusoidal mode.
It would be more correct to call it a convolutional model (the noise component being convolved with the deterministic component and not added as in the traditional source filter model)

**Comment by Ali20177** [comment]
Many thanks for your helpful explanation.

**Comment by gillesdegottex** [comment]
You're welcome!
